# Site properties 
title: Camilo Tejeiro -- Nurture the Joy of Learning
author: Camilo Tejeiro
email: camilo.tejeiro@gmail.com
description: Hardware Electrical Engineer 
# twitter_username: camilotejeiro
github_username:  camilotejeiro

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
gems:
    - jekyll-feed

# Default YAML Front Matter Values
defaults:
  -
    scope:
        path: "_posts" 
    values:
        layout: "post"


