# Site properties 
title: Camilo Tejeiro -- Nurture the Joy of Learning
author: Camilo Tejeiro
email: camilo.tejeiro@gmail.com
description: Hardware Electrical Engineer 
# twitter_username: camilotejeiro
github_username:  camilotejeiro


# Build settings
markdown: kramdown
theme: minima
