# Site properties 
title: Nurture the Joy of Learning
author: Camilo Tejeiro
email: firstname.lastname@gmail.com
description: Hardware Electrical Engineer 
twitter_username: camilotejeiro
github_username:  camilotejeiro

# Build settings
markdown: kramdown
theme: minima
plugins:
    - jekyll-feed
    - jekyll-sitemap

# Default YAML Front Matter Values
defaults:
  -
    scope: 
        path: "_posts" 
    values:
        layout: "post"

